package turkuvaz.sdk.models.Models.Enums;

public enum ClickViewType {
    LAST_MINUTE,
    HEADLINE_SLIDER,
    VIDEO_GALLERY_SLIDER,
    VIDEO_WITH_DESCRIPTION,
    PHOTO_GALLERY_SLIDER,
    NEWS_SNAP,
    NEWS_INFINITY_LIST,
    NOTIFICATIONS_NEWS_LIST,
    COLUMNIST_SLIDER,
    PHOTO_WITH_DESCRIPTION
}
